CREATE TABLE IF NOT EXISTS chat_session (
    session_id VARCHAR(255) PRIMARY KEY,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS chat_turn (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(255) NOT NULL,
    user_content CLOB NOT NULL,
    assistant_content CLOB NOT NULL,
    created_at BIGINT NOT NULL,
    CONSTRAINT fk_chat_turn_session
        FOREIGN KEY (session_id) REFERENCES chat_session(session_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_chat_turn_session_id_id
    ON chat_turn (session_id, id);
